---
# setup disk layout
- name: Default fs type
  set_fact:
    fstype: "ext4"
  when: "'mongodb' not in group_names"

- name: Custom fs type
  set_fact:
    fstype: "xfs"
  when: "'mongodb' in group_names"

# disk
- name: Umount /mnt
  ignore_errors: True
  mount: name=/mnt src=/dev/xvdb fstype=ext4 state=absent

# ssd is a raid0 of the ebs ssd disk
- name: Check if md0 volume is mounted
  shell: cat /proc/mounts | grep /dev/md0
  changed_when: False
  failed_when: False
  register: mounted

- name: Create raid0 volume
  shell: mdadm --create --run --verbose /dev/md0 --level=0 --raid-devices=2 /dev/xvdb /dev/xvdc
  when: mounted.stdout == ""

- name: Format /ssd volume
  shell: "mkfs.{{fstype}} -f /dev/md0"
  when: "mounted.stdout == '' and 'mongodb' in group_names"

- name: Format /ssd volume
  shell: "mkfs.{{fstype}} /dev/md0"
  when: "mounted.stdout == '' and 'mongodb' not in group_names"

- name: Mount /ssd
  mount: name=/ssd fstype={{fstype}} src=/dev/md0 opts=noatime,nodiratime state=mounted
  when: mounted.stdout == ""

- name: Set /ssd read ahead
  # 32 sector is 16k
  shell: blockdev --setra 32 /dev/md0
  when: "mounted.stdout == '' and 'mongodb' in group_names"

- name: Use noop scheduler /ssd
  shell: echo noop > /sys/block/md0/queue/scheduler
  when: mounted.stdout == ""

# ebs is the local
- name: Check if EBS volume is mounted
  shell: cat /proc/mounts | grep /dev/xvdf
  changed_when: False
  failed_when: False
  register: mounted

- name: Format EBS volume
  shell: "mkfs.{{fstype}} /dev/xvdf"
  when: mounted.stdout == ""

- name: Mount EBS volume
  mount: name=/ebs fstype={{fstype}} src=/dev/xvdf opts=noatime,nodiratime state=mounted
  when: mounted.stdout == ""

- name: Set /ebs read ahead
  # 32 sector is 16k
  shell: blockdev --setra 32 /dev/xvdf
  when: "mounted.stdout == '' and 'mongodb' in group_names"

- name: Use noop scheduler /ebs
  shell: echo noop > /sys/block/xvdf/queue/scheduler
  when: mounted.stdout == ""


# hugepage
- name: Disable hugepage defrag
  shell: echo never > /sys/kernel/mm/transparent_hugepage/defrag

- name: Disable hugepage
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled

- name: Disable zone reclaim
  shell: echo 0 > /proc/sys/vm/zone_reclaim_mode
